### ISSUE TITLE
Not working conversion

### ISSUE THREAD

**Issue by Naimas** [joanroig/swatches-to-ase#15]
I have run the conversion but there is no output 👍 
File skipped: .gitkeep
Converting: ANNUNCIATION_LEONARDO_DA_VINCI_.swatches
Converting: LADY_WITH_AN_ERMINE_LEONARDO_DA_VINCI_.swatches
Converting: MADONNA_OF_THE_CARNATION_LEONARDO_DA_VINCI.swatches
Converting: PORTRAIT_OF_THE_GINEVRA_DE_BENCI_LEONARDO_DA_VINCI_.swatches
Converting: SAINT_JEROME_IN_THE_WILDERNESS_LEONARDO_DA_VINCI_.swatches
Converting: ST_JOHN_THE_BAPTIST_LEONARDO_DA_VINCI.swatches
Converting: THE_LAST_SUPPER_LEONARDO_DA_VINCI.swatches
Converting: THE_MONA_LISA_BY_LEONARDO_DA_VINCI.swatches
Converting: THE_VIRGIN_AND_CHILD_WITH_ST_ANNE_LEONARDO_DA_VINCI_.swatches
Converting: VIRGIN_OF_THE_ROCKS_LEONARDO_DA_VINCI.swatches
All done!
l:\Download\swatches-to-ase-main\swatches-to-ase-main\src\index.ts:59
          const name = ColorHelper.findClosestColor(hex).name;
                                   ^

TypeError: ColorHelper.findClosestColor is not a function
    at null.<anonymous> (l:\Download\swatches-to-ase-main\swatches-to-ase-main\src\index.ts:59:36)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)

**Comment by joanroig** [comment]
Hello @Naimas, I have pushed a new version which addresses the issue, please run `npm install` and try again

**Comment by Naimas** [comment]
Thankyou, I will try, does it convert also brushes?

**Comment by joanroig** [comment]
No, this repo is only for swatches

**Comment by Naimas** [comment]
Do you know of one for brushes?

**Comment by joanroig** [comment]
No idea, sorry
