### ISSUE TITLE
Vague Instruction

### ISSUE THREAD

**Issue by enarnia** [joanroig/swatches-to-ase#2]
The install instructions are vague and require a good amount of precious knowledge some Photoshop users do not have: are more detailed instructions possible?

**Comment by enarnia** [comment]
I have managed to install it, but running npm start causes an error of there being no start script to be thrown up

**Comment by lashermayfair** [comment]
You need to run the npm start, from a console in the folder you have the script.

**Comment by joanroig** [comment]
Sorry for the late answer, @lashermayfair answer is correct.

**Comment by enarnia** [comment]
Thanks! I appreciate it.
    On Sunday, February 6, 2022, 08:18:54 AM EST, Joan ***@***.***> wrote:  
 
 


Sorry for the late answer, @lashermayfair answer is correct.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
